services:
    App\Tests\Mercure\NullPublisherFactory: ~
    App\Tests\Support\FakeVeraCli: ~

    App\Vera\VeraCli:
        alias: App\Tests\Support\FakeVeraCli

    # Replace Mercure hub with MockHub in test environment
    mercure.hub.default:
        class: Symfony\Component\Mercure\MockHub
        factory: ['@App\Tests\Mercure\NullPublisherFactory', 'createHub']
